name: LuaRocks release
on:
  push:
    tags: # Will upload to luarocks.org when a tag is pushed
      - "*"
  pull_request: # Will test a local install without uploading to luarocks.org

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      - name: Install tree-sitter CLI
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tree-sitter-cli
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        with:
            dependencies: |
              tree-sitter-apex
              tree-sitter-soql
              tree-sitter-sosl
              nvim-treesitter-legacy-api
              fzf-lua
            test_dependencies: |
              mini.test
            copy_directories: |
              {{ neovim.plugin.dirs }}
              tests
            license: "MIT"
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCK }}
